name: Update Google Sheets from GeoJSON

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas gspread gspread_pandas gspread_dataframe
      - name: Create Google credentials file
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google_credentials.json
      - name: Run script for all files
        env:
          GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python geojson_to_sheets.py --sheet_id "1GvyU-1fu8VEhX-V5_Cf0cMI3-47Sa1PxoXSOQLst4aE" --geojson_path "data/cable.geojson" --branch "main"
          python geojson_to_sheets.py --sheet_id "1f8EP3Nk3qe9VbS1BNIdQyTy2tyAfumikn0qO0m5jPXY" --geojson_path "data/land_cables.geojson" --branch "main"
          python geojson_to_sheets.py --sheet_id "18h39RUQYyK_nyCqcxqz_Vl3hhhLz3odw6t-a7FH9eKw" --geojson_path "data/data_centers.geojson" --branch "main"
          python geojson_to_sheets.py --sheet_id "12g8XmTVcYPAbW0azH7rTRHB_mvKN04zs7xe4P4-Jia8" --geojson_path "data/puntos.geojson" --branch "main"
